### ISSUE TITLE
[SUGGESTION] Use a different branch for development

### ISSUE THREAD

**Issue by Raiden0456** [Comfy-Themes/Spicetify#139] opened 2023-06-23 11:24 UTC
[Screencast from 2023-06-23 17-33-30.webm](https://github.com/Comfy-Themes/Spicetify/assets/41489691/eff99c5e-2d2e-4915-8635-ef6131031ddb)
Yesterday the theme was updated and currently is rewriting [x - library](https://github.com/Comfy-Themes/Spicetify/commit/3aaf687a1bb406665b26ca83526bd8f3c070f5c0). This caused the theme to be extremely laggy for me as i've relied on this library for smooth experience.

**Comment by ohitstom** [comment] 2023-06-23 11:53
> Yesterday the theme was updated and currently is rewriting [x - library](https://github.com/Comfy-Themes/Spicetify/commit/3aaf687a1bb406665b26ca83526bd8f3c070f5c0). This caused the theme to be extremely laggy for me as i've relied on this library for smooth experience.
> 
> 

can you elaborate? I don't see any noticeable lag and didn't change anything that should add some, the reason I didn't make this a pr is because the latest update of Spotify broke thinks so I needed to do a basic patch up before I open a new branch to do the rest.

**Comment by Raiden0456** [comment] 2023-06-23 12:15
> > Yesterday the theme was updated and currently is rewriting [x - library](https://github.com/Comfy-Themes/Spicetify/commit/3aaf687a1bb406665b26ca83526bd8f3c070f5c0). This caused the theme to be extremely laggy for me as i've relied on this library for smooth experience.
> > 
> > 
> 
> can you elaborate? I don't see any noticeable lag and didn't change anything that should add some, the reason I didn't make this a pr is because the latest update of Spotify broke things so I needed to do a basic patch up as soon as possible before I open a new branch to do the rest.

Sure, I'll update the issue with screencast in a couple of hours

**Comment by Raiden0456** [comment] 2023-06-23 16:08
@ohitstom updated description with the video

**Comment by ohitstom** [comment] 2023-06-23 16:57
I doubt that this issue is caused by the css changes I made, can you verify that this isnt being caused by something else please.

**Comment by Raiden0456** [comment] 2023-06-23 17:30
> I doubt that this issue is caused by the css changes I made, can you verify that this isnt being caused by something else please.

I could, just before an option to use X boost (or smth I don't remember exactly) got removed from the settings 😂

**Comment by ohitstom** [comment] 2023-06-23 18:15
yeah no, this isnt a comfy issue, that was support option that has now been merged into the main css instead of being loaded via a setting.

**Comment by ohitstom** [comment] 2023-06-23 18:17
you can try downgrading the theme to the old version to see if that makes a difference but i doubt it, also send your config

**Comment by ohitstom** [comment] 2023-06-25 12:31
closing for inactivity and lack of proof

**Closed by ohitstom** 2023-06-25 12:31 UTC

**Comment by Raiden0456** [comment] 2023-06-25 12:34
> closing for inactivity and lack of proof

My bad I went out of town for a couple of days, I'll reopen the issue once I have proof. Hope I won't need to :)
