### ISSUE TITLE
Play/pause button doesn't look like play/pause button

### ISSUE THREAD

**Issue by ObaMart** [Comfy-Themes/Spicetify#114] opened 2023-02-03 11:34 UTC
![Screenshot_20230203_123331](https://user-images.githubusercontent.com/75756983/216593434-838efa8c-9836-491b-83d5-7fc38b022f1a.png)
![Screenshot_20230203_123338](https://user-images.githubusercontent.com/75756983/216593437-53fca017-072a-4a95-a59f-cde525bef158.png)

Pause button looks like a lot of lines in a sort of pause button formation, play button looks like a triangle with a bite out of it with 2 other lines

**Comment by kyrie25** [comment] 2023-02-03 12:07
Remove `bloom.js` from `config-xpui` and re-apply.

**Comment by kyrie25** [comment] 2023-02-03 12:07
Duplicate of #102

**Closed by kyrie25** 2023-02-03 12:07 UTC

**Comment by ObaMart** [comment] 2023-02-03 12:11
It was a conflict with fluent, removed fluent.js and it's fixed now. So not a `bloom.js` issue, but still thanks for helping me fix it
